#!/usr/bin/bash 
set -e # TO ESCAPE IF ERROR

if ! command -v dmidecode >/dev/null 2>&1; then
	echo "Dependancies Not found.... Installing"

	sudo apt update
	sudo apt install dmidecode -y
fi
sudo dmidecode -t memory | awk -F: '/Configured Memory Speed/ {print $2; exit}' | sed 's/ //' > "./RAM_INFO"
